CREATE SCHEMA IF NOT EXISTS public;

create table if not exists public.users
(
    user_id       int generated by default as identity primary key,
    username      varchar(255) not null,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at    timestamp default CURRENT_TIMESTAMP,
    updated_at    timestamp default CURRENT_TIMESTAMP
);

comment on table public.users is 'Table for storing user information, including login credentials and profile details.';

comment on column public.users.user_id is 'Unique identifier for each user; primary key.';

comment on column public.users.username is 'Username chosen by the user; unique and used for identification within the app.';

comment on column public.users.email is 'User''s email address; used for account verification and communication; unique across all users.';

comment on column public.users.password_hash is 'Hash of the user''s password for secure authentication.';

comment on column public.users.created_at is 'Timestamp indicating when the user account was created.';

comment on column public.users.updated_at is 'Timestamp of the last update made to the user''s account information.';

create table if not exists public.incomes
(
    income_id   int generated by default as identity primary key,
    amount      numeric(10, 2) default 0 not null,
    source      varchar(255)             not null,
    income_date date                     not null,
    description varchar,
    user_id     integer references public.users
);

comment on table public.incomes is 'Table for recording various income sources for users.';

comment on column public.incomes.income_id is 'Unique identifier for each income record; primary key.';

comment on column public.incomes.amount is 'Amount of income received.';

comment on column public.incomes.source is 'Source of income (e.g., salary, rental income).';

comment on column public.incomes.income_date is 'Date when the income was received.';

comment on column public.incomes.description is 'Optional description providing more details about the income source.';

comment on column public.incomes.user_id is 'Identifier of the user receiving the income; foreign key referencing users table.';

create table if not exists public.expenses
(
    expense_id   int generated by default as identity primary key,
    amount       numeric(10, 2) not null,
    category     varchar(255)   not null,
    expense_date date           not null,
    description  text,
    user_id      integer
        references public.users
);

comment on table public.expenses is 'Table for recording the various expenses incurred by users.';

comment on column public.expenses.expense_id is 'Unique identifier for each expense record; primary key.';

comment on column public.expenses.amount is 'Monetary value of the expense.';

comment on column public.expenses.category is 'Category to which the expense belongs (e.g., groceries, utilities).';

comment on column public.expenses.expense_date is 'Date when the expense was incurred.';

comment on column public.expenses.description is 'Optional text description providing more details about the expense.';

comment on column public.expenses.user_id is 'Identifier of the user who incurred the expense; foreign key referencing users table.';

create table if not exists public.savings_goals
(
    saving_goal_id   int generated by default as identity primary key,
    saving_goal_name varchar(255)   not null,
    target_amount    numeric(10, 2) not null,
    current_amount   numeric(10, 2) not null,
    start_date       date           not null,
    end_date         date,
    user_id          integer references public.users
);

comment on table public.savings_goals is 'Table for tracking savings goals set by users.';

comment on column public.savings_goals.saving_goal_id is 'Unique identifier for each savings goal; primary key.';

comment on column public.savings_goals.saving_goal_name is 'Name of the savings goal (e.g., vacation, emergency fund).';

comment on column public.savings_goals.target_amount is 'Target amount to be saved for the goal.';

comment on column public.savings_goals.current_amount is 'Current amount saved towards the goal.';

comment on column public.savings_goals.start_date is 'Start date for the savings goal.';

comment on column public.savings_goals.end_date is 'End date or target date to achieve the savings goal.';

comment on column public.savings_goals.user_id is 'Identifier of the user who set the savings goal; foreign key referencing users table.';

create table if not exists public.budgets
(
    budget_id    int generated by default as identity primary key,
    "month"      int            not null,
    "year"       integer        not null,
    total_budget numeric(10, 2) not null,
    user_id      integer references public.users
);

alter table public.budgets
    add constraint budgets_month_check check ("month" >= 1 AND "month" <= 12);
alter table public.budgets
    add constraint budgets_year_check check ("year" >= 1900);

comment on table public.budgets is 'Table for managing the monthly budgets set by users.';

comment on column public.budgets.budget_id is 'Unique identifier for each budget record; primary key.';

comment on column public.budgets."month" is 'Month for which the budget is set.';

comment on column public.budgets."year" is 'Year for which the budget is set.';

comment on column public.budgets.total_budget is 'Total budget amount set by the user for the specified month and year.';

comment on column public.budgets.user_id is 'Identifier of the user to whom the budget belongs; foreign key referencing users table.';

create table if not exists public.budget_details
(
    budget_details_id int generated by default as identity primary key,
    allocated_amount  numeric(10, 2) not null,
    category          varchar(255)   not null,
    budget_id         integer
        references public.budgets
);

comment on table public.budget_details is 'Table for storing detailed budget allocations for different categories in user budgets.';

comment on column public.budget_details.budget_details_id is 'Unique identifier for each budget detail record; primary key.';

comment on column public.budget_details.allocated_amount is 'Amount allocated to the specific category within the budget.';

comment on column public.budget_details.category is 'Category of the budget allocation (e.g., groceries, entertainment).';

comment on column public.budget_details.budget_id is 'Identifier of the associated budget; foreign key referencing budgets table.';

