create table if not exists public.token
(
    token_id   int generated by default as identity primary key,
    token      varchar(255) unique not null,
    token_type varchar(255)        not null default 'BEARER',
    revoked    boolean             not null default false,
    expired    boolean             not null default false,
    user_id    integer references public.users
);