apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/cash-compass-app-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: LOGGING_LEVEL_ROOT
              value: info
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/financingdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
          image: 192.168.2.80:5000/jzoric/cash-compass-app:2
          name: cash-compass-app
          ports:
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
      restartPolicy: Always
